services:
  timetable:
    image: ubuntu:24.04
    container_name: timetable_app
    environment:
      - TZ=Europe/Berlin
    ports:
      - 5123:5123
    working_dir: /timetable
    volumes:
      - .:/timetable
    command: /bin/bash -c /timetable/execute.sh
